### ISSUE TITLE
To-do Task List

### ISSUE THREAD

**Issue by ha0ye** [annakrystalli/ReScience-reprohack#3]
Things to do or think about for setting up the event:
- [ ] shiny app (to register participants?)
- [ ] event repo (to organize resources and gitter chat)
- [ ] template reScience submission (https://github.com/ReScience/ReScience-submission)
- [ ] instructions for participants to join (finding a local Sprint site or working remotely)
- [ ] instructions for participants during the event (getting started and documenting process)
- [ ] identifying papers and associated code/data resources for computational reproducibility
- [ ] logo and hex stickers (bonus)
